// Arcom v2.1 design tokens, inlined as JS for the React app.
// Same palette as the mockup — sage on navy, warm neutrals, no pure black/white.

export const globalStyles = `
  * { box-sizing: border-box; }
  body, html { margin: 0; padding: 0; }
  button { font-family: inherit; cursor: pointer; border: none; background: none; }
  button:focus-visible, input:focus-visible { outline: 2px solid #FFB627; outline-offset: 2px; }
  button:disabled { cursor: not-allowed; opacity: 0.4; }
  input { font-family: inherit; }
`;

export const styles = {
  root: { display: 'flex', minHeight: '100vh', background: '#FAF7F2', color: '#2B2A27', fontFamily: "'Open Sans', system-ui, sans-serif", fontSize: 14 },
  sidebar: { width: 240, background: '#002B49', color: '#FAF7F2', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  sidebarBrand: { padding: '24px 20px', display: 'flex', alignItems: 'center', gap: 12, borderBottom: '0.5px solid rgba(250,247,242,0.08)' },
  brandMark: { width: 36, height: 36, borderRadius: 8, background: 'rgba(123,160,106,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  brandText: { margin: 0, fontFamily: "'Montserrat', sans-serif", fontWeight: 700, fontSize: 14, letterSpacing: '0.12em' },
  brandSub: { margin: 0, fontSize: 11, color: '#B6CFA9', letterSpacing: '0.04em' },
  nav: { padding: '12px 0', flex: 1 },
  navItem: { width: '100%', padding: '12px 20px', display: 'flex', alignItems: 'center', gap: 12, color: '#FAF7F2', fontSize: 13, fontWeight: 500, fontFamily: "'Montserrat', sans-serif", letterSpacing: '0.02em', position: 'relative', transition: 'background 120ms' },
  navItemActive: { background: 'rgba(123,160,106,0.08)', color: '#B6CFA9' },
  navAccent: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 3, background: '#7BA06A' },
  navIcon: { display: 'flex', alignItems: 'center' },
  sidebarFooter: { padding: '14px 20px', borderTop: '0.5px solid rgba(250,247,242,0.08)', display: 'flex', alignItems: 'center', gap: 10 },
  statusDot: { width: 8, height: 8, borderRadius: '50%', background: '#7BA06A', boxShadow: '0 0 0 3px rgba(123,160,106,0.18)', flexShrink: 0 },
  footerTitle: { margin: 0, fontSize: 12, fontWeight: 500, color: '#FAF7F2' },
  footerSub: { margin: 0, fontSize: 10, color: '#8A8275', fontFamily: "'JetBrains Mono', monospace" },
  signOutBtn: { width: 28, height: 28, borderRadius: 6, color: '#8A8275', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', transition: 'all 120ms' },
  main: { flex: 1, padding: '40px 40px 64px', minWidth: 0 },
  masthead: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 24, marginBottom: 14 },
  eyebrow: { margin: 0, fontFamily: "'Montserrat', sans-serif", fontSize: 10, fontWeight: 500, letterSpacing: '0.12em', color: '#567B49', textTransform: 'uppercase' },
  title: { margin: '4px 0 0', fontFamily: "'Montserrat', sans-serif", fontSize: 26, fontWeight: 600, color: '#2B2A27', letterSpacing: '-0.01em' },
  mastMeta: { textAlign: 'right' },
  metaLabel: { fontFamily: "'Montserrat', sans-serif", fontSize: 10, fontWeight: 500, letterSpacing: '0.12em', color: '#8A8275' },
  metaValue: { marginTop: 4, fontFamily: "'JetBrains Mono', monospace", fontSize: 13, color: '#2B2A27' },
  mastRule: { height: 2, background: '#7BA06A', marginBottom: 24 },
  stats: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12, marginBottom: 28 },
  tile: { background: '#FFFFFF', border: '0.5px solid #E4DDCF', borderRadius: 12, padding: 18 },
  tileEyebrow: { margin: 0, fontFamily: "'Montserrat', sans-serif", fontSize: 10, fontWeight: 500, letterSpacing: '0.08em', color: '#567B49', textTransform: 'uppercase' },
  tileValue: { margin: '8px 0 4px', fontFamily: "'JetBrains Mono', monospace", fontSize: 28, fontWeight: 500, fontVariantNumeric: 'tabular-nums', lineHeight: 1 },
  tileSub: { margin: 0, fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#8A8275' },
  toolbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, gap: 12 },
  toolbarLeft: { display: 'flex', gap: 12 },
  viewToggle: { display: 'flex', background: '#F4EFE6', borderRadius: 999, padding: 3, border: '0.5px solid #E4DDCF' },
  viewBtn: { padding: '7px 14px', fontSize: 12, fontWeight: 500, fontFamily: "'Montserrat', sans-serif", letterSpacing: '0.04em', color: '#8A8275', borderRadius: 999, display: 'inline-flex', alignItems: 'center', gap: 6, transition: 'all 120ms' },
  viewBtnActive: { background: '#FFFFFF', color: '#002B49', boxShadow: '0 1px 2px rgba(0,43,73,0.06)' },
  btnPrimary: { background: '#002B49', color: '#FAF7F2', height: 40, padding: '0 18px', borderRadius: 999, fontFamily: "'Montserrat', sans-serif", fontSize: 13, fontWeight: 500, letterSpacing: '0.04em', display: 'inline-flex', alignItems: 'center', gap: 8, transition: 'filter 120ms' },
  btnGhost: { background: 'transparent', color: '#002B49', height: 36, padding: '0 14px', borderRadius: 999, border: '0.5px solid #002B49', fontFamily: "'Montserrat', sans-serif", fontSize: 12, fontWeight: 500, letterSpacing: '0.04em', display: 'inline-flex', alignItems: 'center', gap: 6, transition: 'background 120ms' },
  btnGhostSm: { background: 'transparent', color: '#567B49', height: 32, padding: '0 12px', borderRadius: 999, border: '0.5px solid #B6CFA9', fontFamily: "'Montserrat', sans-serif", fontSize: 11, fontWeight: 500, letterSpacing: '0.04em', display: 'inline-flex', alignItems: 'center', gap: 6, marginTop: 8, transition: 'all 120ms' },
  btnDanger: { background: '#B3432B', color: '#FAF7F2', height: 36, padding: '0 14px', borderRadius: 999, fontFamily: "'Montserrat', sans-serif", fontSize: 12, fontWeight: 500, letterSpacing: '0.04em', display: 'inline-flex', alignItems: 'center', gap: 6 },
  btnDangerGhost: { background: 'transparent', color: '#B3432B', height: 36, padding: '0 14px', borderRadius: 999, border: '0.5px solid #B3432B', fontFamily: "'Montserrat', sans-serif", fontSize: 12, fontWeight: 500, letterSpacing: '0.04em', display: 'inline-flex', alignItems: 'center', gap: 6 },
  btnDisabled: { opacity: 0.4, cursor: 'not-allowed' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16 },
  card: { background: '#FFFFFF', border: '0.5px solid #E4DDCF', borderRadius: 12, overflow: 'hidden', transition: 'box-shadow 120ms, transform 120ms', display: 'flex', flexDirection: 'column' },
  cardPreview: { position: 'relative', aspectRatio: '16 / 9', background: '#F4EFE6', borderBottom: '0.5px solid #E4DDCF', cursor: 'pointer', overflow: 'hidden' },
  cardScreenshot: { width: '100%', height: '100%', objectFit: 'cover', display: 'block' },
  statusChip: { position: 'absolute', top: 10, left: 10, fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 500, letterSpacing: '0.08em', padding: '4px 8px', borderRadius: 999, display: 'inline-flex', alignItems: 'center', gap: 4 },
  chipOnline: { background: '#7BA06A', color: '#002B49' },
  chipOffline: { background: '#B3432B', color: '#FAF7F2' },
  rotationBadge: { position: 'absolute', top: 10, right: 10, background: 'rgba(0,43,73,0.85)', color: '#FAF7F2', fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 500, letterSpacing: '0.08em', padding: '4px 8px', borderRadius: 999, display: 'inline-flex', alignItems: 'center', gap: 4 },
  rotationInline: { display: 'inline-flex', alignItems: 'center', gap: 6, color: '#1E5079', fontFamily: "'Open Sans', sans-serif", fontSize: 12, fontWeight: 500 },
  cardBody: { padding: 16, display: 'flex', flexDirection: 'column', gap: 10, flex: 1 },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  cardName: { margin: 0, fontFamily: "'Montserrat', sans-serif", fontWeight: 600, fontSize: 14, color: '#2B2A27' },
  cardHost: { margin: '2px 0 0', fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: '#8A8275' },
  cardUrlRow: { display: 'flex', alignItems: 'center', gap: 6, padding: '6px 8px', background: '#F4EFE6', borderRadius: 6, overflow: 'hidden' },
  cardUrl: { fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#2B2A27', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  cardFoot: { flex: 1 },
  cardMeta: { display: 'flex', alignItems: 'center', gap: 6, fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: '#8A8275' },
  cardMetaDot: { color: '#C7BEAE' },
  cardActions: { display: 'flex', gap: 6, paddingTop: 4 },
  tableWrap: { background: '#FFFFFF', border: '0.5px solid #E4DDCF', borderRadius: 12, overflow: 'hidden' },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: { fontFamily: "'Montserrat', sans-serif", fontSize: 10, fontWeight: 500, letterSpacing: '0.08em', color: '#567B49', textAlign: 'left', padding: '14px 16px', borderBottom: '0.5px solid #E4DDCF', background: '#FAF7F2' },
  thNum: { textAlign: 'right' },
  tr: { transition: 'background 120ms' },
  td: { padding: '14px 16px', borderBottom: '0.5px solid #E4DDCF', fontSize: 13, color: '#2B2A27' },
  tdMono: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12 },
  tdNum: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12, fontVariantNumeric: 'tabular-nums', textAlign: 'right' },
  tdUrl: { maxWidth: 300, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: '#1E5079' },
  linkBtn: { fontFamily: "'Montserrat', sans-serif", fontWeight: 500, fontSize: 13, color: '#002B49', padding: 0 },
  statusChipInline: { fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 500, letterSpacing: '0.08em', padding: '3px 8px', borderRadius: 999, display: 'inline-block' },
  tableActions: { display: 'inline-flex', gap: 4 },
  iconBtn: { width: 30, height: 30, borderRadius: 6, color: '#8A8275', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', transition: 'all 120ms' },
  modalScrim: { position: 'fixed', inset: 0, background: 'rgba(0,43,73,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, zIndex: 100 },
  modal: { background: '#FAF7F2', borderRadius: 14, width: '100%', maxWidth: 540, maxHeight: '90vh', display: 'flex', flexDirection: 'column', boxShadow: '0 12px 48px rgba(0,43,73,0.24)', overflow: 'hidden' },
  modalHead: { padding: '20px 24px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, borderBottom: '0.5px solid #E4DDCF' },
  modalTitle: { margin: '4px 0 0', fontFamily: "'Montserrat', sans-serif", fontSize: 20, fontWeight: 600, color: '#2B2A27' },
  modalClose: { width: 32, height: 32, borderRadius: 8, color: '#8A8275', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'background 120ms' },
  modalBody: { padding: '20px 24px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 14 },
  modalFoot: { padding: '16px 24px', borderTop: '0.5px solid #E4DDCF', background: '#FFFFFF', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  footRight: { display: 'flex', gap: 8 },
  confirmRow: { display: 'flex', alignItems: 'center', gap: 8 },
  confirmText: { fontSize: 12, color: '#B3432B', fontWeight: 500 },
  field: { display: 'flex', flexDirection: 'column', gap: 6 },
  fieldRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 },
  fieldLabel: { fontFamily: "'Montserrat', sans-serif", fontSize: 11, fontWeight: 500, letterSpacing: '0.04em', color: '#567B49', textTransform: 'uppercase' },
  fieldHint: { margin: '4px 0 0', fontSize: 11, color: '#8A8275', lineHeight: 1.5 },
  input: { height: 40, padding: '0 14px', border: '0.5px solid #E4DDCF', borderRadius: 8, background: '#FFFFFF', color: '#2B2A27', fontFamily: "'Open Sans', sans-serif", fontSize: 14, transition: 'border-color 120ms' },
  metaCard: { background: '#F4EFE6', borderRadius: 8, padding: '14px 16px', display: 'flex', flexDirection: 'column', gap: 8, marginTop: 4 },
  metaCardRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 12 },
  metaCardKey: { color: '#8A8275', fontFamily: "'Montserrat', sans-serif", fontWeight: 500, fontSize: 11, letterSpacing: '0.04em', textTransform: 'uppercase' },
  metaCardVal: { fontFamily: "'JetBrains Mono', monospace", color: '#2B2A27' },
  helperBanner: { background: '#F4EFE6', borderLeft: '3px solid #7BA06A', borderRadius: 6, padding: '12px 14px', display: 'flex', alignItems: 'flex-start', gap: 10, fontSize: 12, color: '#2B2A27', lineHeight: 1.5, marginTop: 4 },
  urlsHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, gap: 12 },
  rotationHint: { display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 10, color: '#1E5079', fontFamily: "'Open Sans', sans-serif", fontStyle: 'italic' },
  urlsList: { display: 'flex', flexDirection: 'column', gap: 8 },
  urlRow: { display: 'flex', alignItems: 'center', gap: 8, padding: 8, background: '#FFFFFF', border: '0.5px solid #E4DDCF', borderRadius: 8 },
  urlOrder: { width: 24, flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  urlOrderNum: { width: 24, height: 24, background: '#002B49', color: '#FAF7F2', borderRadius: '50%', fontFamily: "'JetBrains Mono', monospace", fontSize: 11, fontWeight: 500, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' },
  urlInputs: { flex: 1, display: 'flex', gap: 8, minWidth: 0 },
  urlInput: { flex: 1, minWidth: 0 },
  durationField: { position: 'relative', flexShrink: 0, width: 100 },
  durationInput: { width: '100%', paddingRight: 38 },
  durationLabel: { position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)', fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#8A8275', pointerEvents: 'none' },
  urlControls: { display: 'flex', gap: 2, flexShrink: 0 },
  urlIconBtn: { width: 28, height: 28, borderRadius: 6, color: '#8A8275', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', transition: 'background 120ms, color 120ms' },
  previewBody: { padding: 24 },
  rotationTabs: { display: 'flex', gap: 6, marginBottom: 16, flexWrap: 'wrap' },
  rotationTab: { background: '#F4EFE6', border: '0.5px solid #E4DDCF', color: '#8A8275', height: 32, padding: '0 12px', borderRadius: 999, fontFamily: "'Open Sans', sans-serif", fontSize: 12, fontWeight: 500, display: 'inline-flex', alignItems: 'center', gap: 6, transition: 'all 120ms' },
  rotationTabActive: { background: '#FFFFFF', color: '#002B49', borderColor: '#002B49' },
  rotationTabNum: { width: 18, height: 18, borderRadius: '50%', background: '#002B49', color: '#FAF7F2', fontFamily: "'JetBrains Mono', monospace", fontSize: 10, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' },
  rotationTabDuration: { fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: '#8A8275' },
  previewFrame: { aspectRatio: '16 / 9', background: '#002B49', borderRadius: 8, padding: 8, overflow: 'hidden' },
  previewImage: { width: '100%', height: '100%', objectFit: 'contain', borderRadius: 4 },
  previewCaption: { marginTop: 14, fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#8A8275', textAlign: 'center' },
  drawerScrim: { position: 'fixed', inset: 0, background: 'rgba(0,43,73,0.45)', display: 'flex', justifyContent: 'flex-end', zIndex: 100 },
  drawer: { width: 420, maxWidth: '90vw', background: '#FAF7F2', display: 'flex', flexDirection: 'column', height: '100vh', boxShadow: '-12px 0 48px rgba(0,43,73,0.24)' },
  drawerHead: { padding: '24px 24px 16px', borderBottom: '0.5px solid #E4DDCF', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 },
  drawerBody: { padding: '20px 24px', flex: 1, overflowY: 'auto' },
  drawerFoot: { padding: 20, borderTop: '0.5px solid #E4DDCF', display: 'flex', gap: 8, justifyContent: 'flex-end' },
  detailRow: { padding: '12px 0', borderBottom: '0.5px solid #E4DDCF', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  detailKey: { fontFamily: "'Montserrat', sans-serif", fontSize: 11, fontWeight: 500, letterSpacing: '0.04em', color: '#8A8275', textTransform: 'uppercase' },
  detailVal: { fontSize: 13, color: '#2B2A27', textAlign: 'right', overflow: 'hidden', textOverflow: 'ellipsis' },
  detailValMono: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12 },
  rotationDetail: { padding: '12px 0', borderBottom: '0.5px solid #E4DDCF' },
  rotationDetailHead: { margin: '0 0 10px', fontFamily: "'Montserrat', sans-serif", fontSize: 11, fontWeight: 500, letterSpacing: '0.04em', color: '#8A8275', textTransform: 'uppercase' },
  rotationDetailRow: { display: 'flex', alignItems: 'center', gap: 10, padding: '8px 0' },
  rotationDetailNum: { width: 22, height: 22, background: '#002B49', color: '#FAF7F2', borderRadius: '50%', fontFamily: "'JetBrains Mono', monospace", fontSize: 10, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  rotationDetailUrl: { flex: 1, fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#2B2A27', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  rotationDetailDur: { fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#8A8275', flexShrink: 0 },
  filterRow: { display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 16 },
  filterChip: { background: '#F4EFE6', border: '0.5px solid #E4DDCF', color: '#8A8275', height: 30, padding: '0 14px', borderRadius: 999, fontFamily: "'Montserrat', sans-serif", fontSize: 12, fontWeight: 500, letterSpacing: '0.02em', transition: 'all 120ms' },
  filterChipActive: { background: '#002B49', color: '#FAF7F2', borderColor: '#002B49' },
  activityList: { background: '#FFFFFF', border: '0.5px solid #E4DDCF', borderRadius: 12, overflow: 'hidden' },
  activityRow: { display: 'flex', alignItems: 'center', gap: 14, padding: '14px 18px', borderBottom: '0.5px solid #E4DDCF', transition: 'background 120ms' },
  activityIcon: { width: 32, height: 32, borderRadius: 8, background: '#F4EFE6', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  activityMain: { flex: 1, minWidth: 0 },
  activityTop: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 2 },
  activityScreen: { fontFamily: "'Montserrat', sans-serif", fontWeight: 600, fontSize: 13, color: '#2B2A27' },
  activityType: { fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 500, letterSpacing: '0.08em', color: '#8A8275' },
  activityDetail: { margin: 0, fontSize: 12, color: '#8A8275', lineHeight: 1.5 },
  activityMeta: { textAlign: 'right', flexShrink: 0 },
  activityUser: { margin: 0, fontSize: 12, fontWeight: 500, color: '#2B2A27', fontFamily: "'Montserrat', sans-serif" },
  activityTime: { margin: '2px 0 0', fontSize: 10, color: '#8A8275', fontFamily: "'JetBrains Mono', monospace" },
  emptyState: { background: '#FFFFFF', border: '0.5px solid #E4DDCF', borderRadius: 12, padding: '48px 24px', textAlign: 'center' },
  emptyText: { margin: 0, color: '#8A8275', fontSize: 13 },
  toast: { position: 'fixed', bottom: 24, right: 24, background: '#002B49', color: '#FAF7F2', padding: '12px 18px', borderRadius: 999, fontSize: 13, fontFamily: "'Montserrat', sans-serif", fontWeight: 500, boxShadow: '0 8px 24px rgba(0,43,73,0.3)', display: 'flex', alignItems: 'center', gap: 8, zIndex: 200 },
};
